### PR TITLE
Leaflet 1.0 compatible version

### PR DESCRIPTION
**Pull request by mstahv**
Stuff done by @octavm, but against my fork.

I'd do a short testing and build e.g. 1.0.0.b1 version for usage with (V-)Leaflet 1.0 branches.

### CODE REVIEW

**Comment by normandhenault** [comment]
Hi ya Matti

I use Ivy.xml and so far I only see a markercluster version compatible with leaflet 0.5.5 on the Vaadin site. Shall I wait a little more until th version is changed ?

This version chang e will be hugely beneficial for my project :)

Cheers

Norm.

Envoyé de mon iPad

Le 18 nov. 2015 à 08:19, Matti Tahvonen <notifications@github.com<mailto:notifications@github.com>> a écrit :


Stuff done by @octavm<https://github.com/octavm>, but against my fork.

I'd do a short testing and build e.g. 1.0.0.b1 version for usage with (V-)Leaflet 1.0 branches.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/willtemperley/v-leaflet-markercluster-parent/pull/5

Commit Summary

  *   Update MarkerClusterGroup.java
  *   Create MarkerClusterGroupOptions.java
  *   Update leaflet.markercluster.js
  *   Update leaflet.markercluster-src.js
  *   Update MarkerCluster.css
  *   Update pom.xml
  *   Update LeafletMarkerClusterConnector.java
  *   Create LeafletMarkerClusterState.java
  *   Update LMarkerClusterGroup.java
  *   Update pom.xml
  *   Merge pull request #1 from octavm/master
  *   Merge branch 'master' of github.com:mstahv/v-leaflet-markercluster-parent

File Changes

  *   M g-leaflet-markercluster/pom.xml<https://github.com/willtemperley/v-leaflet-markercluster-parent/pull/5/files#diff-0> (2)
  *   M g-leaflet-markercluster/src/main/java/org/vaadin/gleaflet/markercluster/client/MarkerClusterGroup.java<https://github.com/willtemperley/v-leaflet-markercluster-parent/pull/5/files#diff-1> (7)
  *   A g-leaflet-markercluster/src/main/java/org/vaadin/gleaflet/markercluster/client/MarkerClusterGroupOptions.java<https://github.com/willtemperley/v-leaflet-markercluster-parent/pull/5/files#diff-2> (59)
  *   M g-leaflet-markercluster/src/main/resources/org/vaadin/gleaflet/markercluster/client/resources/MarkerCluster.css<https://github.com/willtemperley/v-leaflet-markercluster-parent/pull/5/files#diff-3> (7)
  *   M g-leaflet-markercluster/src/main/resources/org/vaadin/gleaflet/markercluster/client/resources/leaflet.markercluster-src.js<https://github.com/willtemperley/v-leaflet-markercluster-parent/pull/5/files#diff-4> (4130)
  *   M g-leaflet-markercluster/src/main/resources/org/vaadin/gleaflet/markercluster/client/resources/leaflet.markercluster.js<https://github.com/willtemperley/v-leaflet-markercluster-parent/pull/5/files#diff-5> (2)
  *   M v-leaflet-markercluster/pom.xml<https://github.com/willtemperley/v-leaflet-markercluster-parent/pull/5/files#diff-6> (4)
  *   M v-leaflet-markercluster/src/main/java/org/vaadin/addon/leaflet/markercluster/LMarkerClusterGroup.java<https://github.com/willtemperley/v-leaflet-markercluster-parent/pull/5/files#diff-7> (42)
  *   M v-leaflet-markercluster/src/main/java/org/vaadin/addon/leaflet/markercluster/client/LeafletMarkerClusterConnector.java<https://github.com/willtemperley/v-leaflet-markercluster-parent/pull/5/files#diff-8> (45)
  *   A v-leaflet-markercluster/src/main/java/org/vaadin/addon/leaflet/markercluster/client/LeafletMarkerClusterState.java<https://github.com/willtemperley/v-leaflet-markercluster-parent/pull/5/files#diff-9> (18)

Patch Links:

  *   https://github.com/willtemperley/v-leaflet-markercluster-parent/pull/5.patch
  *   https://github.com/willtemperley/v-leaflet-markercluster-parent/pull/5.diff

-

**Comment by mstahv** [comment]
Although I don't personally use this add-on in my projects, I know this is essential for many Vaadin users. I hope @willtemperley will find a moment to cut a release soon. The only other option would be to create a fork with different name to vaadin.com/directory (or publish a release to e.g. maven central).

**Comment by normandhenault** [comment]
Go Will go !!! (Loud cheers)

;)

Envoyé de mon iPad

Le 18 nov. 2015 à 10:13, Matti Tahvonen <notifications@github.com<mailto:notifications@github.com>> a écrit :


Although I don't personally use this add-on in my projects, I know this is essential for many Vaadin users. I hope @willtemperley<https://github.com/willtemperley> will find a moment to cut a release soon. The only other option would be to create a fork with different name to vaadin.com/directory<http://vaadin.com/directory> (or publish a release to e.g. maven central).

-

**Comment by mstahv** [comment]
The problem is I only have GitHub to connect to @willtemperley, I bet he would do the new release if he'd just notice the new stuff :-) If somebody knows his email/phone/whatever, please ping him about these changes.

**Comment by octavm** [comment]
@mstahv could you cut a release from your own branch, and maybe continue the development there ?
It looks like the project here is dead, last commit, is 1 year ago.

**Comment by mstahv** [comment]
Hmm. I'd have fork the name as well because the Directory don't allow to highjack add-on ownership. Let's do that if we can't reach @willtemperley in near future.

**Comment by willtemperley** [comment]
Apologies, merged, I've been away from Vaadin stuff for a while

**Comment by normandhenault** [comment]
Hi ya folks,

So, when is the Leaflet 1.0 compatible version of MarkerCluster available on vaadin/download ?

Cheers.

Norm.

**Comment by willtemperley** [comment]
There's one there now, built against v-leaflet beta4

**Pull request merged**
